# Generated by Django 3.0.4 on 2022-06-03 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hob_nombre', models.CharField(choices=[('Ir al cine', 'Ir al cine'), ('Playa', 'Playa'), ('Comida', 'Comida')], max_length=30, verbose_name='Hobbies')),
            ],
            options={
                'verbose_name': 'Hobbie',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pac_nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre invalido,verifique que no contenga letras o simbolos', regex='^[A-Za-z ]{3,50}$')], verbose_name='Nombre')),
                ('pac_apellido', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El apellido ingresado es invalido,verifique que no contenga letras o simbolos', regex='^[A-Za-z ]{3,50}$')], verbose_name='Apellidos')),
                ('pac_direccion', models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(message='Direccion incorrecta, verifique que esta bien escrita', regex='^[A-Za-z0-9 #-.]{10,100}$')], verbose_name='Direccion')),
                ('pac_telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Numero telefonico digitado incorrectamente, verifique que no tenga letras ni simbolos', regex='^([\\d]{5,5})\\s?([\\d]){5,5}$')], verbose_name='Telefono')),
                ('pac_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gen_nombre', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=30, verbose_name='Genero')),
                ('estr_nombre', models.CharField(choices=[('Estrato 1', 'Estrato 1'), ('Estrato 2', 'Estrato 2'), ('Estrato 3', 'Estrato 3')], max_length=30, verbose_name='Estrato')),
                ('hob_nombre', models.ManyToManyField(to='patients.Hobbies')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='medicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_motv', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo de Visita')),
                ('hist_esfod', models.CharField(max_length=50, verbose_name='Esfera OD')),
                ('hist_cilod', models.CharField(max_length=50, verbose_name='Cilindro OD')),
                ('hist_ejeod', models.CharField(max_length=50, verbose_name='Eje OD')),
                ('hist_esfoi', models.CharField(max_length=50, verbose_name='Esfera OI')),
                ('hist_ciloi', models.CharField(max_length=50, verbose_name='Cilindro OI')),
                ('hist_ejeoi', models.CharField(max_length=50, verbose_name='Eje OI')),
                ('hist_diaod', models.CharField(max_length=50, verbose_name='Diagnostico ojo derecho')),
                ('hist_diaoi', models.CharField(max_length=50, verbose_name='Diagnostico ojo izquierdo')),
                ('hist_recom', models.CharField(blank=True, max_length=500, null=True, verbose_name='Recomendaciones')),
                ('pac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia Clinica',
                'verbose_name_plural': 'Historias Clinicas',
            },
        ),
    ]
