# Generated by Django 2.2.24 on 2022-06-13 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pac_nit',
            field=models.IntegerField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de identificacion es incorrecto,verifique que no contenga letras o simbololos', regex='^([\\d]{1,5})\\s?([\\d]){5,7}$')], verbose_name='Documento de identidad'),
            preserve_default=False,
        ),
    ]
