# Generated by Django 2.2.24 on 2022-06-13 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_pac_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pac_nit',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='El numero de identificacion es incorrecto,verifique que no contenga letras o simbololos', regex='^([\\d]{1,5})\\s?([\\d]){5,7}$')], verbose_name='Documento de identidad'),
        ),
    ]
